services:
  ansible:
    image: ansible
    container_name: ansible
    working_dir: /ansible
    environment:
      - ANSIBLE_SSH_ARGS="-o StrictHostKeyChecking=no"
    volumes:
      - ./conf:/ansible
      - ./keys:/root/.ssh
    network_mode: host
    entrypoint: ["ansible-playbook"]
